# Generated by Django 4.2.7 on 2025-12-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', 'number']},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='year',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semester',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.department'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('department', 'year', 'number')},
        ),
    ]
